export const categories = [
  {
    name: "Automotive",
    subcategories: [
      "Car Parts",
      "Motorcycles",
      "Tires & Wheels",
      "Car Electronics",
      "Accessories",
    ],
    iconClass: "fas fa-car",
  },
  {
    name: "Building & Industry",
    subcategories: [
      "Building & Industrial Machinery",
      "Building Materials",
      "Fuel Materials",
      "Photovoltaics",
      "Power Generators",
      "Power Tools",
      "Redecoration & Renovation Products",
      "Sanitary Fittings",
      "Tools",
      "Workwear & PPE",
    ],
    iconClass: "fas fa-hard-hat",
  },
  {
    name: "Clothing",
    subcategories: [
      "Men's Clothing",
      "Women's Clothing",
      "Kids' Clothing",
      "Shoes",
      "Accessories",
    ],
    iconClass: "fas fa-tshirt",
  },
  {
    name: "Consumer Electronics",
    subcategories: [
      "Mobile Phones",
      "Laptops & Computers",
      "Cameras & Photography",
      "Audio Devices",
      "Wearable Technology",
    ],
    iconClass: "fas fa-laptop",
  },
  {
    name: "Food & Beverage",
    subcategories: [
      "Snacks & Sweets",
      "Beverages",
      "Organic Food",
      "Dairy Products",
      "Canned Goods",
    ],
    iconClass: "fas fa-utensils",
  },
  {
    name: "For Children",
    subcategories: [
      "Toys",
      "Baby Clothing",
      "Educational Products",
      "Strollers & Carriers",
      "Nursery Furniture",
    ],
    iconClass: "fas fa-baby-carriage",
  },
  {
    name: "Furniture",
    subcategories: [
      "Living Room Furniture",
      "Bedroom Furniture",
      "Office Furniture",
      "Outdoor Furniture",
      "Decor",
    ],
    iconClass: "fas fa-couch",
  },
  {
    name: "Health & Beauty",
    subcategories: [
      "Skincare",
      "Makeup",
      "Hair Care",
      "Personal Care",
      "Wellness Products",
    ],
    iconClass: "fas fa-heart",
  },
  {
    name: "Home, Garden & Office",
    subcategories: [
      "Kitchen Appliances",
      "Home Decor",
      "Gardening Tools",
      "Office Supplies",
      "Cleaning Supplies",
    ],
    iconClass: "fas fa-home",
  },
  {
    name: "Major Appliances & White Goods",
    subcategories: [
      "Refrigerators",
      "Washing Machines",
      "Air Conditioners",
      "Cooking Appliances",
      "Dishwashers",
    ],
    iconClass: "fas fa-cogs",
  },
  {
    name: "Phones & Mobile Phones",
    subcategories: [
      "Smartphones",
      "Feature Phones",
      "Phone Accessories",
      "Smart Watches",
      "Chargers & Batteries",
    ],
    iconClass: "fas fa-mobile-alt",
  },
  {
    name: "Shoes",
    subcategories: [
      "Men's Shoes",
      "Women's Shoes",
      "Kids' Shoes",
      "Sneakers",
      "Boots",
    ],
    iconClass: "fas fa-shoe-prints",
  },
  {
    name: "Small Appliances",
    subcategories: [
      "Vacuum Cleaners",
      "Blenders & Mixers",
      "Coffee Makers",
      "Toasters",
      "Microwaves",
    ],
    iconClass: "fas fa-blender",
  },
];
